# This file should contain all the record creation needed to seed the database
# with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the
# db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Trip.create([
              { name: 'Bad Martha\'s Farmer\'s Brewery',
                location: 'Edgartown, Massachusetts',
                description: '',
                photo: 'https://i.imgur.com/wnGXhfL.jpg',
                spring: true,
                summer: true,
                fall: true,
                boozy: true,
                outdoorsy: true,
                dist_from_bos: 2 },

              { name: 'Crane Beach',
                location: 'Ipswich, Massachusetts',
                description: '',
                photo: 'https://i.imgur.com/3p69eLq.jpg',
                summer: true,
                outdoorsy: true,
                dist_from_bos: 1 },

              { name: 'Edgartown',
                location: 'Edgartown, Massachusetts',
                description: '',
                photo: 'https://i.imgur.com/zdB8smQ.jpg',
                spring: true,
                summer: true,
                foodie: true,
                artsy: true,
                outdoorsy: true,
                dist_from_bos: 2 },

              { name: 'Good Harbor',
                location: 'Gloucester, Massachusetts',
                description: '',
                photo: 'https://i.imgur.com/UC1w1Dw.jpg',
                spring: true,
                summer: true,
                fall: true,
                foodie: true,
                outdoorsy: true,
                dist_from_bos: 1 },

              { name: 'Middlesex Fells Reservation',
                location: 'Stoneham, Massachusetts',
                description: '',
                photo: 'https://i.imgur.com/uHsG6zB.jpg',
                summer: true,
                outdoorsy: true,
                dist_from_bos: 0.5 },

              { name: 'Nashoba Valley Winery',
                location: 'Bolton, Massachusetts',
                description: '',
                photo: 'https://i.imgur.com/1ozeux7.jpg',
                spring: true,
                summer: true,
                fall: true,
                boozy: true,
                outdoorsy: true,
                dist_from_bos: 1 },

              { name: 'Newport',
                location: 'Newport, Rhode Island',
                description: '',
                photo: 'https://i.imgur.com/uLXKoxV.jpg',
                spring: true,
                summer: true,
                fall: true,
                winter: true,
                artsy: true,
                foodie: true,
                outdoorsy: true,
                boozy: true,
                dist_from_bos: 1.5 },

              { name: 'Rockport',
                location: 'Rockport, Massachusetts',
                description: '',
                photo: 'https://i.imgur.com/AzN4cHO.jpg',
                spring: true,
                summer: true,
                fall: true,
                artsy: true,
                foodie: true,
                dist_from_bos: 1 },

              { name: 'Stoney Brook Reservation',
                location: 'Hyde Park, Massachusetts',
                description: '',
                photo: 'https://i.imgur.com/s5yEPj9.jpg',
                spring: true,
                summer: true,
                fall: true,
                outdoorsy: true,
                dist_from_bos: 0.5 },

              { name: 'Tree House Brewing Co.',
                location: 'Monson, Massachusetts',
                description: '',
                photo: 'https://i.imgur.com/DHymzq2.jpg',
                spring: true,
                summer: true,
                fall: true,
                boozy: true,
                outdoorsy: true,
                dist_from_bos: 1.5 },

              { name: 'The Town of Salem',
                location: 'Salem, Massachusetts',
                description: '',
                photo: 'https://i.imgur.com/CsqzCAc.jpg',
                spring: true,
                summer: true,
                fall: true,
                winter: true,
                artsy: true,
                foodie: true,
                dist_from_bos: 1 },

              { name: 'Wachusett Mountain',
                location: 'Princeton, Massachusetts',
                description: '',
                photo: 'https://i.imgur.com/CSSRBLB.jpg',
                winter: true,
                outdoorsy: true,
                dist_from_bos: 1.5 },

              { name: 'Westport Rivers Vineyards',
                location: 'Westport, Massachusetts',
                description: '',
                photo: 'https://i.imgur.com/1ozeux7.jpg',
                spring: true,
                summer: true,
                fall: true,
                boozy: true,
                outdoorsy: true,
                dist_from_bos: 1.5 },

              { name: 'Wright Locke Farm',
                location: 'Winchester, Massachusetts',
                description: '',
                photo: 'https://i.imgur.com/POomQzM.jpg',
                spring: true,
                summer: true,
                fall: true,
                foodie: true,
                outdoorsy: true,
                dist_from_bos: 0.5 }
            ])
